stages:
  - build
  - release


build:
  stage: build
  image: docker
  services: [ "docker:dind" ]
  script:
    - apk update && apk add make
    - sed -i 's/RUNNER := podman/RUNNER := docker/' Makefile 
    - make build-tex-img 
    - make gen-documents 
  after_script:
    - echo "JOB_URL=$CI_JOB_URL" >> job.env
  artifacts:
    paths:
      - documents/
  reports:
    dotenv: job.env 

do_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 
  needs:
    - job: build 
      artifacts: true
  script:
    - echo "running release_job"
  variables:
    TAG: '$CI_COMMIT_TAG'
  release:                               
    name: "Entrega de la $TAG"
    tag_name: '$TAG'
    description: 'Entrega de la $TAG'
    assets:
      links:
        - name: "$TAG.pdf"
          url: "$JOB_URL/artifacts/file/documents/$TAG/$TAG.pdf"
